name = "bccs-club-frontend"
compatibility_date = "2024-09-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]
